server:
  port: 89
  context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_play_house?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false


lucenePath: C://lucene
# 游戏封面图片路径
gameCoverImageFilePath: D://phImage/gameCoverImage/
# 游戏内容图片路径
gameContentImageFilePath: D://phImage/gameContentImage/

# 用户头像路径
userImageFilePath: D://userImages/

#lucenePath: /home/lucene

#articleImageFilePath: /home/articleImages/

#userImageFilePath: /home/userImages/