server:
  port: 89
  context-path: /
  tomcat:
    uri-encoding: UTF-8

# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_play_house?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    maode: LEGACYHTML5
    content-type: text/html
  mail:
    host: smtp.qq.com
    username: 166768601@qq.com
    password: zivatvjkuzkebhca
    default-encoding: UTF-8
    port: 465
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.properties.mail.debug: true
# redis配置
redis:
   hostName: 192.168.0.105
   port: 6379
   password: 123456
   maxIdle: 100
   maxTotal: 200
   maxWaitMillis: 1000 
   testOnBorrow: true

# 资源封面图片路径
coverImageFilePath: D://phImage/coverImage/
# 资源内容图片路径
contentImageFilePath: D://phImage/contentImage/
# 用户头像路径
userHeadFilePath: D://phImage/userHeadFilePath/
# 索引存储路径-游戏
lucenePath1: D://lucene1
# 索引存储路径-软件
lucenePath2: D://lucene2

#日志配置
logging:
  config.classpath: log4j2.xml
  #level.org.springframework: error
  #level.org.hibernate: error 